package com.sabi.bikes.domain.enumeration;

/**
 * The PartCategoryType enumeration.
 */
public enum PartCategoryType {
    STEMS, HANDLEBARS, HEADSET, SADDLE, SEAT_POST, SEAT_CLAMP, DERAILLEUR, CHAINS, CRANKSETS, PEDALS, STRAPS, TYRES, ALLOY_CARBON_WHEELS, WIRE_SPOKED_WHEELS, BOYAUX, BRAKE_LEVERS, BRAKE_CABLES, BRAKE_CALIPERS, BRAKE_PADS, FRAME_KITS, FRAMES, FORKS
}
