version: '2'
services:
  sabike-app:
    image: sabike
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://sabike-postgresql:5432/Sabike
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  sabike-postgresql:
    extends:
      file: postgresql.yml
      service: sabike-postgresql
